
icons_format = "{icon}"

[theme]
theme = "ctp-mocha"

[icons]
icons = "awesome4"

[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:1)"

[[block]]
block = "disk_space"

[[block]]
block = "net"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
